# Generated by Django 5.2.9 on 2026-01-08 14:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=128, verbose_name='工具名称')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='工具描述')),
                ('tool_type', models.CharField(max_length=32, verbose_name='工具类型')),
                ('tool_config', models.JSONField(default=dict, verbose_name='工具配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('is_system', models.BooleanField(default=False, verbose_name='是否系统工具')),
            ],
            options={
                'verbose_name': '工具',
                'verbose_name_plural': '工具',
                'db_table': 'tcm_tool',
            },
        ),
        migrations.CreateModel(
            name='MCPTool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('mcp_server_url', models.CharField(max_length=512, verbose_name='MCP服务器地址')),
                ('mcp_config', models.JSONField(default=dict, verbose_name='MCP配置')),
                ('tool_schema', models.JSONField(default=dict, verbose_name='工具Schema')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.tool', verbose_name='工具')),
            ],
            options={
                'verbose_name': 'MCP工具',
                'verbose_name_plural': 'MCP工具',
                'db_table': 'tcm_mcp_tool',
            },
        ),
    ]
