# Generated by Django 5.2.9 on 2026-01-18 14:59

import apps.knowledge.models
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=128, verbose_name='知识库名称')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='知识库描述')),
                ('meta', models.JSONField(blank=True, default=dict, null=True, verbose_name='元数据')),
                ('user_id', models.UUIDField(verbose_name='用户ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('embedding_model', models.CharField(default='shibing624/text2vec-base-chinese', max_length=128, verbose_name='嵌入模型')),
                ('embedding_dimension', models.IntegerField(default=768, verbose_name='向量维度')),
                ('similarity_threshold', models.FloatField(default=0.5, verbose_name='相似度阈值')),
                ('search_type', models.CharField(choices=[('embedding', '向量搜索'), ('keywords', '关键词搜索'), ('blend', '混合搜索')], default='blend', max_length=16, verbose_name='搜索模式')),
                ('top_k', models.IntegerField(default=5, verbose_name='返回结果数量')),
            ],
            options={
                'verbose_name': '知识库',
                'verbose_name_plural': '知识库',
                'db_table': 'tcm_knowledge_base',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=255, verbose_name='文档名称')),
                ('file_type', models.CharField(max_length=32, verbose_name='文件类型')),
                ('file_size', models.BigIntegerField(verbose_name='文件大小')),
                ('file_path', models.CharField(max_length=512, verbose_name='文件路径')),
                ('char_count', models.IntegerField(default=0, verbose_name='字符数')),
                ('paragraph_count', models.IntegerField(default=0, verbose_name='段落数')),
                ('status', models.CharField(default='processing', max_length=32, verbose_name='处理状态')),
                ('progress', models.IntegerField(default=0, verbose_name='处理进度(0-100)')),
                ('meta', models.JSONField(blank=True, default=dict, null=True, verbose_name='元数据')),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge.knowledgebase', verbose_name='知识库')),
            ],
            options={
                'verbose_name': '文档',
                'verbose_name_plural': '文档',
                'db_table': 'tcm_document',
            },
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('content', models.TextField(verbose_name='段落内容')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='标题')),
                ('page_number', models.IntegerField(blank=True, null=True, verbose_name='页码')),
                ('meta', models.JSONField(blank=True, default=dict, null=True, verbose_name='元数据')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge.document', verbose_name='文档')),
            ],
            options={
                'verbose_name': '段落',
                'verbose_name_plural': '段落',
                'db_table': 'tcm_paragraph',
            },
        ),
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='主键id')),
                ('source_id', models.CharField(db_index=True, max_length=128, verbose_name='资源id')),
                ('source_type', models.CharField(db_index=True, max_length=5, verbose_name='资源类型')),
                ('is_active', models.BooleanField(default=True, max_length=1, verbose_name='是否可用')),
                ('embedding', apps.knowledge.models.VectorField(verbose_name='向量')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(default='', verbose_name='分词')),
                ('meta', models.JSONField(default=dict, verbose_name='元数据')),
                ('document', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='knowledge.document', verbose_name='文档关联')),
                ('knowledge', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='knowledge.knowledgebase', verbose_name='知识库关联')),
                ('paragraph', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='knowledge.paragraph', verbose_name='段落关联')),
            ],
            options={
                'verbose_name': '嵌入',
                'verbose_name_plural': '嵌入',
                'db_table': 'tcm_embedding',
            },
        ),
    ]
