# Generated by Django 5.2.9 on 2026-01-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebase',
            name='user_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='用户ID'),
        ),
    ]
