# Generated by Django 5.2.9 on 2026-01-08 14:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=128, verbose_name='应用名称')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='应用描述')),
                ('icon', models.CharField(blank=True, max_length=512, null=True, verbose_name='图标')),
                ('user_id', models.UUIDField(verbose_name='用户ID')),
                ('work_flow', models.JSONField(default=dict, verbose_name='工作流配置')),
                ('model_config', models.JSONField(default=dict, verbose_name='模型配置')),
                ('knowledge_bases', models.JSONField(default=list, verbose_name='关联知识库')),
                ('tools', models.JSONField(default=list, verbose_name='关联工具')),
                ('prompt_template', models.TextField(blank=True, null=True, verbose_name='提示词模板')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
            ],
            options={
                'verbose_name': '应用',
                'verbose_name_plural': '应用',
                'db_table': 'tcm_application',
            },
        ),
        migrations.CreateModel(
            name='WorkflowEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('source_node', models.CharField(max_length=64, verbose_name='源节点ID')),
                ('target_node', models.CharField(max_length=64, verbose_name='目标节点ID')),
                ('edge_data', models.JSONField(default=dict, verbose_name='边数据')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.application', verbose_name='应用')),
            ],
            options={
                'verbose_name': '工作流边',
                'verbose_name_plural': '工作流边',
                'db_table': 'tcm_workflow_edge',
            },
        ),
        migrations.CreateModel(
            name='WorkflowNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('node_id', models.CharField(max_length=64, verbose_name='节点ID')),
                ('node_type', models.CharField(max_length=32, verbose_name='节点类型')),
                ('node_data', models.JSONField(default=dict, verbose_name='节点数据')),
                ('position', models.JSONField(default=dict, verbose_name='位置信息')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.application', verbose_name='应用')),
            ],
            options={
                'verbose_name': '工作流节点',
                'verbose_name_plural': '工作流节点',
                'db_table': 'tcm_workflow_node',
            },
        ),
    ]
