# Generated by Django 5.2.9 on 2026-01-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='prompt_template_type',
            field=models.CharField(default='DEFAULT', max_length=64, verbose_name='提示词模板类型'),
        ),
        migrations.AddField(
            model_name='application',
            name='similarity_threshold',
            field=models.FloatField(default=0.5, verbose_name='相似度阈值，低于该值不使用知识库内容'),
        ),
        migrations.AddField(
            model_name='application',
            name='system_prompt',
            field=models.TextField(blank=True, null=True, verbose_name='系统提示词'),
        ),
    ]
