# Generated by Django 5.2.9 on 2026-01-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_application_prompt_template_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='icon',
            field=models.CharField(blank=True, max_length=8192, null=True, verbose_name='图标'),
        ),
    ]
