# Generated by Django 5.2.9 on 2026-01-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_application_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='icon',
            field=models.TextField(blank=True, null=True, verbose_name='图标'),
        ),
    ]
