# Generated by Django 5.2.9 on 2026-01-10 15:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_application_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationAPIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=64, verbose_name='API密钥名称')),
                ('api_key', models.CharField(max_length=256, unique=True, verbose_name='API密钥')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('usage_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.application', verbose_name='关联应用')),
            ],
            options={
                'verbose_name': '应用API密钥',
                'verbose_name_plural': '应用API密钥',
                'db_table': 'tcm_application_api_key',
            },
        ),
    ]
