# Generated by Django 5.2.9 on 2026-01-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_applicationapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='top_k',
            field=models.IntegerField(default=5, verbose_name='引用分段数(top)'),
        ),
    ]
