# Generated by Django 5.2.9 on 2026-01-11 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_application_top_k'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='user_id',
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='application',
            name='icon',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='application',
            name='top_k',
            field=models.IntegerField(default=5, verbose_name='检索返回数量'),
        ),
    ]
