# Generated by Django 5.2.9 on 2026-01-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_remove_application_user_id_application_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='top_k',
        ),
        migrations.AlterField(
            model_name='application',
            name='icon',
            field=models.TextField(blank=True, null=True, verbose_name='图标'),
        ),
        migrations.DeleteModel(
            name='ApplicationAPIKey',
        ),
    ]
