# Generated by Django 5.2.9 on 2026-01-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('model_type', models.CharField(default='LLM', max_length=50, verbose_name='模型类型')),
                ('provider', models.CharField(max_length=50, verbose_name='模型提供商')),
                ('model_name', models.CharField(max_length=100, verbose_name='模型标识')),
                ('credential', models.JSONField(verbose_name='认证信息')),
                ('params', models.JSONField(default=dict, verbose_name='模型参数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '模型配置',
                'verbose_name_plural': '模型配置',
                'ordering': ['-create_time'],
            },
        ),
    ]
