# Generated by Django 5.2.9 on 2026-01-08 14:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('application_id', models.UUIDField(verbose_name='应用ID')),
                ('user_id', models.UUIDField(verbose_name='用户ID')),
                ('session_name', models.CharField(max_length=128, verbose_name='会话名称')),
                ('meta', models.JSONField(blank=True, default=dict, null=True, verbose_name='元数据')),
            ],
            options={
                'verbose_name': '聊天会话',
                'verbose_name_plural': '聊天会话',
                'db_table': 'tcm_chat_session',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('role', models.CharField(max_length=16, verbose_name='角色')),
                ('content', models.TextField(verbose_name='内容')),
                ('message_type', models.CharField(default='text', max_length=32, verbose_name='消息类型')),
                ('meta', models.JSONField(blank=True, default=dict, null=True, verbose_name='元数据')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatsession', verbose_name='会话')),
            ],
            options={
                'verbose_name': '聊天消息',
                'verbose_name_plural': '聊天消息',
                'db_table': 'tcm_chat_message',
            },
        ),
    ]
