# Generated by Django 5.2.9 on 2026-01-15 13:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='主键id')),
                ('file_name', models.CharField(default='', max_length=256, verbose_name='文件名称')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小')),
                ('sha256_hash', models.CharField(default='', max_length=64, verbose_name='文件sha256_hash标识')),
                ('source_type', models.CharField(choices=[('KNOWLEDGE', 'Knowledge'), ('APPLICATION', 'Application'), ('TOOL', 'Tool'), ('DOCUMENT', 'Document'), ('CHAT', 'Chat'), ('SYSTEM', 'System'), ('TEMPORARY_30_MINUTE', 'Temporary 30 Minute'), ('TEMPORARY_120_MINUTE', 'Temporary 120 Minute'), ('TEMPORARY_1_DAY', 'Temporary 1 Day')], db_index=True, default='TEMPORARY_120_MINUTE', verbose_name='资源类型')),
                ('source_id', models.CharField(db_index=True, default='TEMPORARY_120_MINUTE', verbose_name='资源id')),
                ('meta', models.JSONField(default=dict, verbose_name='文件关联数据')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '文件',
                'verbose_name_plural': '文件',
                'db_table': 'file',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-create_time'], 'verbose_name': '聊天消息', 'verbose_name_plural': '聊天消息'},
        ),
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-create_time'], 'verbose_name': '聊天会话', 'verbose_name_plural': '聊天会话'},
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='update_time',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='files',
            field=models.JSONField(default=list, verbose_name='关联文件'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='主键id'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(default='text', max_length=50, verbose_name='消息类型'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='meta',
            field=models.JSONField(default=dict, verbose_name='元数据'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(choices=[('user', 'assistant')], default='user', max_length=20, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession', verbose_name='会话'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='application_id',
            field=models.CharField(max_length=128, verbose_name='应用ID'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='主键id'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='meta',
            field=models.JSONField(default=dict, verbose_name='元数据'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='session_name',
            field=models.CharField(default='新建对话', max_length=256, verbose_name='会话名称'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='user_id',
            field=models.CharField(max_length=128, verbose_name='用户ID'),
        ),
        migrations.AlterModelTable(
            name='chatmessage',
            table='chat_message',
        ),
        migrations.AlterModelTable(
            name='chatsession',
            table='chat_session',
        ),
    ]
